### ISSUE TITLE
v0.88.1で出力したVRMアバターをBlenderにインポートする時にエラー

### ISSUE THREAD

**Issue by kuni-0930** [vrm-c/UniVRM#1383]
## 環境情報

 - UniVRM version: `0.88.1`
 - Unity version: `Unity-2019.4.31f1`
 - Blender:'2.83'
 - VRM_IMPORTER_for_Blender:'1.90'
 - OS: `Windows 10`

## バグについて
VRoidv1.0.0をunityに入れ、v0.88.1で出力したアバターをBlenderにインポートする時にエラー発生して弾かれます。
ボーンのノードポジション？がおかしいのでしょうか
UniVRMv0.70.0で同様の手順を踏んだところ問題なくBlenderで読み込むことができました

Blenderのエラーログ↓
bpy.context.space_data.system_folders_active = 1
bpy.ops.import_scene.vrm(filepath="D:\\work_blender\\アバター\\アバター10h.vrm")
Traceback (most recent call last):
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-0-17-0\tools\importer.py", line 100, in execute
    self.import_file(self.directory, file_name)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-0-17-0\tools\importer.py", line 202, in import_file
    filepath=file_path)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: エラー: Traceback (most recent call last):
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\__init__.py", line 84, in execute
    blend_model.BlendModel(context, vrm_load.read_vrm(self.filepath, self), self)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm_load.py", line 127, in read_vrm
    node_read(vrm_pydata)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm_load.py", line 431, in node_read
    vrm_pydata.nodes_dict[i] = vrm2pydata_factory.bone(node)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm2pydata_factory.py", line 17, in bone
    v_node.position = node["translation"]
KeyError: 'translation'

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:199
location: <unknown location>:-1
bpy.ops.cats_importer.import_any_model(filepath="D:\\work_blender\\アバター\\アバター10h.vrm", files=[{"name":"アバター10h.vrm", "name":"アバター10h.vrm"}], directory="D:\\work_blender\\アバター\\")
bpy.ops.import_scene.vrm(filepath="D:\\work_blender\\アバター\\アバター10h.vrm")
Traceback (most recent call last):
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-0-17-0\tools\importer.py", line 100, in execute
    self.import_file(self.directory, file_name)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-0-17-0\tools\importer.py", line 202, in import_file
    filepath=file_path)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: エラー: Traceback (most recent call last):
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\__init__.py", line 84, in execute
    blend_model.BlendModel(context, vrm_load.read_vrm(self.filepath, self), self)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm_load.py", line 127, in read_vrm
    node_read(vrm_pydata)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm_load.py", line 431, in node_read
    vrm_pydata.nodes_dict[i] = vrm2pydata_factory.bone(node)
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm2pydata_factory.py", line 17, in bone
    v_node.position = node["translation"]
KeyError: 'translation'

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:199
location: <unknown location>:-1
bpy.ops.cats_importer.import_any_model(filepath="D:\\work_blender\\アバター\\アバター10h.vrm", files=[{"name":"アバター10h.vrm", "name":"アバター10h.vrm"}], directory="D:\\work_blender\\アバター\\")

**Comment by ousttrue** [comment]
報告ありがとうございます。

```
v_node.position = node["translation"]
KeyError: 'translation'
```

は python のエラーです。gltf では node["translation"] は省略することが許容されていて、
最近のバージョンでは `[0, 0, 0]` を省略するようにしました。
Blender のスクリプトの方に修正を依頼してみてください。

省略時のデフォルト値を加味して以下のようにすればよいと思われます。

```python
node["translation"]
👇
node.get("translation", [0, 0, 0])
# rotation, scale もあれば
node.get("rotation", [0, 0, 0, 1])
node.get("scale", [1, 1, 1])
```

**Comment by kuni-0930** [comment]
かしこまりました。
ありがとうございます。

ちなみに0.88から出力したアバターは他のアプリケーションでも読み込めない不具合が挙げられているようです。
詳細が解らないし、本件とは関係ないかもしれないので、本件はここでcloseします。

**Comment by saturday06** [comment]
現在BlenderのVRMアドオンをメンテしているものです。こちらアドオンのバグになります。お手数おかけしてすみません。

アドオンを最新化することでエラーが無くなるはずなので、最新化して再確認お願いします。
https://github.com/saturday06/VRM_IMPORTER_for_Blender
（今年の二月にアドオン名とインストール方法が変わったので、そこだけ注意お願いします）
