### ISSUE TITLE
VRM10 Fails UWP Hololens 2 Build: IL2CPP error

### ISSUE THREAD

**Issue by sipkode** [vrm-c/UniVRM#1866]
## Environments (please complete the following information):

 - VRM10 version: `0.105.0`
 - Unity version: `Unity-2021.3.6f1`
 - OS: `Windows 10`

## Describe the bug

When attempting to build a Unity project after importing the VRM10 packages,
[VRM-0.105.0_cd48.unitypackage](https://github.com/vrm-c/UniVRM/releases/download/v0.105.0/VRM-0.105.0_cd48.unitypackage)
[VRM_Samples-0.105.0_cd48.unitypackage](https://github.com/vrm-c/UniVRM/releases/download/v0.105.0/VRM_Samples-0.105.0_cd48.unitypackage)
the build will fail when attempting to build with IL2CPP for the UWP platform on ARM64, with the following error:

```
Error: IL2CPP error for type 'VRMShaders.PathObject' in C:/Users/Admin/Dev/DoreiChan/Assets/VRMShaders/GLTF/IO/Runtime/PathObject.cs:22
System.NotSupportedException: The type 'VRMShaders.PathObject' contains a static field which has a type of 'System.Nullable`1<VRMShaders.PathObject>'. IL2CPP does not support conversion of this recursively defined type.
   at Unity.IL2CPP.TypeDefinitionWriter.VerifyTypeDoesNotHaveRecursiveStaticNullableFieldDefinitionRecusrive(TypeDefinition typeDefinition, HashSet`1 parentTypes)
   at Unity.IL2CPP.TypeDefinitionWriter.WriteTypeDefinitionFor(ReadOnlyContext context, TypeReference type, IReadOnlyContextGeneratedCodeWriter writer, TypeReference[]& typesRequiringInteropGuids)
   at Unity.IL2CPP.CppDeclarations.CppDeclarationDataModelInitializers.BuildCacheData(ReadOnlyContext context, TypeReference type)
   at Unity.IL2CPP.DataModel.TypeReference.Unity.IL2CPP.DataModel.InjectedInitialize.ITypeReferenceInjectedInitialize.GetCppDeclarationsData[TContext](TContext context, Func`3 initialize)
   at Unity.IL2CPP.CppDeclarations.CppDeclarationDataModelInitializers.GetCppDeclarations(ReadOnlyContext context, ITypeReferenceInjectedInitialize type)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Unity.IL2CPP.CppDeclarations.CppDeclarationsWriter.CollectDeclarations(SourceWritingContext context, ICppDeclarations declarationsIn, CppDeclarations& declarations)
   at Unity.IL2CPP.CppDeclarations.CppDeclarationsWriter.Write(SourceWritingContext context, ICodeStream writer, ICppDeclarations declarationsIn, Boolean addInteropGuids)
   at Unity.IL2CPP.CodeWriters.ManagedSourceCodeWriter.Dispose()
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`2.FlushStream(GlobalWriteContext context, IGeneratedMethodCodeStream stream, NPath filePath)
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`3.WorkerWriteItemsToFile(WorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
 
```

**Comment by ousttrue** [comment]
Thank you for reporting

`static PathObject? _root;`
This code may be the problem.

I'm going to rewrite it to not use Nullable
